## Homework 1: Introduction to Machine Learning for Machine Learning Zoomcamp 2025

### Importing the dependencies

In [2]:
import pandas as pd
import numpy as np

### Getting the data simple via pandas

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [4]:
# Check the simaple data with top 5
df.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q1. Pandas version
What's the version of Pandas that you installed?

You can get the version information using the __version__ field:

In [24]:
# Check my current pandas version
pd.__version__

'2.3.1'

### Getting the data
For this homework, we'll use the Car Fuel Efficiency dataset. Download it from here.

You can do it with wget: 

In [ ]:
# Read the CSV data file
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/car_fuel_efficiency.csv')

In [26]:
# Show the top 5 rows data
df.head(5)

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Q2. Records count
How many records are in the dataset?

In [ ]:
# Count the records number from df


### Q3. Fuel types
How many fuel types are presented in the dataset?

In [27]:
# Count the number of the fuel types in df


### Q4. Missing values
How many columns in the dataset have missing values?

In [ ]:
# Count the number of missing value columns



Bad pipe message: %s [b'"Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium"']
Bad pipe message: %s [b'="139"\r\nsec-ch-ua-mobile: ?0\r\nsec-ch-ua-platform: "macOS"\r']
Bad pipe message: %s [b'ol: max-age=0\r\nsec-ch-ua: "Not;A=Brand";v="99", "Google Chrome";v="139", "Chromium";v="139"\r\nsec-ch-ua-mobile: ?0\r\n']
Bad pipe message: %s [b'c-ch-ua-platform: "macOS"\r\nUpgrade-Insecure-Requests: 1\r\nUser-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_', b' AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0.0', b' Safari/537.36\r\nAccept: text/html,application']
Bad pipe message: %s [b'html+xml,application/xml;q=0.9,image/avif,imag']


### Q5. Max fuel efficiency
What's the maximum fuel efficiency of cars from Asia?

In [ ]:
# Check the maximum fuel efficiency of cars from Asia


### Q6. Median value of horsepower
1. Find the median value of horsepower column in the dataset.
2. Next, calculate the most frequent value of the same horsepower column.
3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step.
4. Now, calculate the median value of horsepower once again.

Has it changed?

In [ ]:
# Check whether the median value of horsepower has been changed after the 3 steps


### Q7. Sum of weights
1. Select all the cars from Asia
2. Select only columns vehicle_weight and model_year
3. Select the first 7 values
4. Get the underlying NumPy array. Let's call it X.
5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
6. Invert XTX.
7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200].
8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
9. What's the sum of all the elements of the result?

> Note: You just implemented linear regression. We'll talk about it in the next lesson.

In [ ]:
# Count the sum of all the elemnets after the 8 steps


In [7]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [8]:
a = np.array([[1,2,3],[4,5,6]])

In [9]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [11]:
np.linspace(0,1,11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [12]:
np.random.seed(10)
np.random.randint(low=0,high=100,size=(5,2))

array([[ 9, 15],
       [64, 28],
       [89, 93],
       [29,  8],
       [73,  0]])

In [13]:
np.random.seed(10)
np.random.rand(5,2)

array([[0.77132064, 0.02075195],
       [0.63364823, 0.74880388],
       [0.49850701, 0.22479665],
       [0.19806286, 0.76053071],
       [0.16911084, 0.08833981]])

In [14]:
u = np.array([2,4,5,6])
v = np.array([1,0,0,2])


In [15]:
a.std()

np.float64(1.707825127659933)

In [16]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]
    result = 0.0
    
    for i in range(n):
        result = result + u[i]*v[i]
    return result

In [17]:
U = np.array([
    [2,4,5,6],
    [1,2,1,2],
    [3,1,2,1],]
              )

In [18]:
V =np.array([
    [1,1,2],
    [0,0.5,1],
    [0,2,1],
]) 

In [19]:
print(vector_vector_multiplication(u,v))

14.0


In [20]:
u.dot(v)

np.int64(14)

In [21]:
U[0]

array([2, 4, 5, 6])

In [22]:
def matrix_vector_multiplication(U,v):
    assert U.shape[1] == v.shape[0]

    num_rows = U.shape[0]

    result = np.zeros(num_rows)

    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i],v)

    return result
    

In [23]:
print(matrix_vector_multiplication(U,v))

[14.  5.  5.]
